In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd /content/drive/MyDrive

/content/drive/MyDrive


In [3]:
!git clone https://github.com/DavidReveloLuna/keras-retinanet.git

fatal: destination path 'keras-retinanet' already exists and is not an empty directory.


In [4]:
!pip uninstall keras -y
!pip uninstall keras-nightly -y
!pip uninstall keras-Preprocessing -y
!pip uninstall keras-vis -y
!pip uninstall tensorflow -y
!pip uninstall h5py

Found existing installation: keras 2.6.0
Uninstalling keras-2.6.0:
  Successfully uninstalled keras-2.6.0
Found existing installation: Keras-Preprocessing 1.1.2
Uninstalling Keras-Preprocessing-1.1.2:
  Successfully uninstalled Keras-Preprocessing-1.1.2
Found existing installation: keras-vis 0.4.1
Uninstalling keras-vis-0.4.1:
  Successfully uninstalled keras-vis-0.4.1
Found existing installation: tensorflow 2.6.0
Uninstalling tensorflow-2.6.0:
  Successfully uninstalled tensorflow-2.6.0
Found existing installation: h5py 3.1.0
Uninstalling h5py-3.1.0:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/h5py-3.1.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libaec-9c9e97eb.so.0.0.10
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libhdf5-00e8fae8.so.200.0.0
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libhdf5_hl-383c339f.so.200.0.0
    /usr/local/lib/python3.7/dist-packages/h5py.libs/libsz-e7aa62f5.so.2.0.1
    /usr/local/lib/python3.7/dist-packa

In [5]:
!pip install tensorflow==2.1.0
!pip install keras==2.3.1
!pip install h5py==2.10.0

     |████████████████████████████████| 421.8 MB 26 kB/s 
     |████████████████████████████████| 50 kB 6.1 MB/s 
     |████████████████████████████████| 42 kB 1.2 MB/s 
     |████████████████████████████████| 3.8 MB 32.2 MB/s 
     |████████████████████████████████| 448 kB 44.6 MB/s 
     |████████████████████████████████| 4.1 MB 29.4 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=cbafc5d1c193c495dc290a37c620002ba04a0357f53d96cb547f20762f0326cf
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.6.0
    Uninstalling tensorflow-estimator-2.6.0:
      Successfully uninstalled tensorflow-estimator-2.6.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.6.0
    Uninstalling tensorboard-2.6.0:
      Successfully uninstalled tensorboard-2.6.0


In [6]:
cd /content/drive/MyDrive/keras-retinanet


/content/drive/MyDrive/keras-retinanet


In [7]:
!pip install .

Processing /content/drive/MyDrive/keras-retinanet
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Created wheel for keras-retinanet: filename=keras_retinanet-0.5.1-cp37-cp37m-linux_x86_64.whl size=170919 sha256=ac4ca8bd0d8075283da22658f7cf1fa5177f4d78853d90665adc42751a341681
  Stored in directory: /root/.cache/pip/wheels/df/f0/c0/f0be69773cd57d10ff1be03f1c25114803973fff6060e9e608
  Created wheel for keras-resnet: filename=keras_resnet-0.1.0-py2.py3-none-any.whl size=13344 sha256=7c49a5970b309e9521a28f2ed4cc55b75c6b7d20a94fdcde91e2613bb1c0738f
  Stored in directory: /root/.cache/pip/wheels/a6/20/57/d7b7be8556e2ebf36345b3df4068a9a13bb90e4a2cc85

In [8]:
!python setup.py build_ext --inplace

running build_ext
skipping 'keras_retinanet/utils/compute_overlap.c' Cython extension (up-to-date)
copying build/lib.linux-x86_64-3.7/keras_retinanet/utils/compute_overlap.cpython-37m-x86_64-linux-gnu.so -> keras_retinanet/utils


In [9]:
import numpy as np
import pandas as pd
import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
from pandas.plotting import register_matplotlib_converters
from sklearn.model_selection import train_test_split
import urllib
import os
import csv
import cv2
import time
from PIL import Image

from tensorflow.keras.models import load_model
from keras_retinanet import models
from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
from keras_retinanet.utils.visualization import draw_box, draw_caption
from keras_retinanet.utils.colors import label_color

# Descargamos modelo preentrenado resnet50_coco
URL_MODEL = 'https://github.com/fizyr/keras-retinanet/releases/download/0.5.1/resnet50_coco_best_v2.1.0.h5'
urllib.request.urlretrieve(URL_MODEL, './snapshots/model.h5')

('./snapshots/model.h5', <http.client.HTTPMessage at 0x7f502508e2d0>)

In [ ]:
!chmod 777 keras_retinanet/bin/*
!keras_retinanet/bin/train.py --freeze-backbone --random-transform --weights snapshots/model.h5 --batch-size 8 --steps 200 --epochs 300 --lr 0.001 csv rudok_vehicles_train3.csv classes_rudok_vehicles.csv
#!keras_retinanet/bin/train.py --freeze-backbone --random-transform --weights snapshots/resnet50_csv_34.h5 --batch-size 8 --steps 500 --epochs 300 csv srijab_train_5.csv classes_srijab.csv

Using TensorFlow backend.
2021-09-02 05:01:14.211746: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-09-02 05:01:14.211866: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-09-02 05:01:14.211892: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Creating model, this may take a second...
2021-09-02 05:01:15.375505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1


In [ ]:
model_path = os.path.join("/content/drive/MyDrive/keras-retinanet/snapshots/resnet50_csv_59.h5")
print(model_path)

model = models.load_model(model_path, backbone_name='resnet50')
model = models.convert_model(model)


labels_to_names = pd.read_csv('/content/drive/MyDrive/keras-retinanet/solar_classes.csv', header=None).T.loc[0].to_dict()


test_df = pd.read_csv("/content/drive/MyDrive/keras-retinanet/solar_test_new9_annotations.csv")
test_df.head()


import skimage.io as io

def predict(image):
  image = preprocess_image(image.copy())
  image, scale = resize_image(image)

  boxes, scores, labels = model.predict_on_batch(
    np.expand_dims(image, axis=0)
  )

  boxes /= scale

  return boxes, scores, labels


umbralScore = 0.2



def draw_detections(image, boxes, scores, labels):
  for box, score, label in zip(boxes[0], scores[0], labels[0]):
    if score < umbralScore:
        break

    color = label_color(label)

    b = box.astype(int)
    draw_box(image, b, color=color)

    caption = "{} {:.3f}".format(labels_to_names[label], score)
    draw_caption(image, b, caption)


for index, row in test_df.iterrows():
  print(row[0], index)
  image = io.imread(row[0])

  boxes, scores, labels = predict(image)

  draw = image.copy()
  draw_detections(draw, boxes, scores, labels)
  plt.imsave('test_saaves_oneim.png',draw)

  plt.axis('off')

  plt.imshow(draw)
  
  plt.show()

/content/drive/MyDrive/keras-retinanet/snapshots/resnet50_csv_59.h5


Using TensorFlow backend.


OSError: ignored

In [ ]:
!keras_retinanet/bin/predict.py --model snapshots/

In [ ]:

# import keras_retinanet
from keras_retinanet import models
from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
from keras_retinanet.utils.visualization import draw_box, draw_caption
from keras_retinanet.utils.colors import label_color
from keras_retinanet.utils.gpu import setup_gpu

# import miscellaneous modules
import matplotlib.pyplot as plt
import cv2
import os
import numpy as np
import time
from PIL import Image
from natsort import natsorted

# set tf backend to allow memory to grow, instead of claiming everything
import tensorflow as tf



# In[ ]:


# adjust this to point to your downloaded/trained model

model_path = "/content/drive/MyDrive/srijab/weights/resnet50_csv_34.h5"
image_path="/content/drive/MyDrive/srijab/srijab_jpg_patches"
out_path="/content/drive/MyDrive/out"
# load retinanet model
model = models.load_model(model_path, backbone_name='resnet50')
model = models.convert_model(model)


# if the model is not converted to an inference model, use the line below
# see: https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model
# model = models.convert_model(model)

#print(model.summary())

# load label to names mapping for visualization purposes
labels_to_names = {0: '0'}


# ## Run detection on example

# In[ ]:


# load image
images=[]
image_no=1
i=1
for image in natsorted(os.listdir(image_path)):
    image=os.path.join(image_path,image)
    image = read_image_bgr(image)
    draw = image.copy()
    draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)
    image = preprocess_image(image)
    image, scale = resize_image(image)
    
    start = time.time()
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
    images.append(image)
    print("processing time: ", time.time() - start)
    boxes /= scale
 

    for box, score, label in zip(boxes[0], scores[0], labels[0]):
        if score < 0.2:
          break

        color = label_color(label)

        b = box.astype(int)
        draw_box(draw, b, color=color)

        #caption = "{} {:.3f}".format(labels_to_names[label], score)
        #draw_caption(draw, b, caption)
        

        plt.imsave('/content/drive/MyDrive/srijab/detect_patches/%d.jpg'%(len(images)),draw)


tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-22.627417, -11.313708,  22.627417,  11.313708],
       [-28.50876 , -14.25438 ,  28.50876 ,  14.25438 ],
       [-35.918785, -17.959393,  35.918785,  17.959393],
       [-16.      , -16.      ,  16.      ,  16.      ],
       [-20.158737, -20.158737,  20.158737,  20.158737],
       [-25.398417, -25.398417,  25.398417,  25.398417],
       [-11.313708, -22.627417,  11.313708,  22.627417],
       [-14.25438 , -28.50876 ,  14.25438 ,  28.50876 ],
       [-17.959393, -35.918785,  17.959393,  35.918785]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-45.254833, -22.627417,  45.254833,  22.627417],
       [-57.01752 , -28.50876 ,  57.01752 ,  28.50876 ],
       [-71.83757 , -35.918785,  71.83757 ,  35.918785],
       [-32.      , -32.      ,  32.      ,  32.      ],
       [-40.317474, -40.317474,  40.317474,  40.317474],
       [-50.796833, -50.796833,  50.7

In [ ]:

from keras_retinanet import models
from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image
from keras_retinanet.utils.visualization import draw_box, draw_caption
from keras_retinanet.utils.colors import label_color
from keras_retinanet.utils.gpu import setup_gpu

import matplotlib.pyplot as plt
import cv2
import os
import numpy as np
import time
from PIL import Image
from natsort import natsorted
import tensorflow as tf

model_path = "/content/drive/MyDrive/weights/resnet50_csv_200.h5"
image_path="/content/drive/MyDrive/Rutok/jpg_patches"

model = models.load_model(model_path, backbone_name='resnet50')
model = models.convert_model(model)

#print(model.summary())

LABELS = {0:'Vehicle'}

images=[]
for image in natsorted(os.listdir(image_path)):
    filename = (image.split(os.path.sep)[-1]).split('.')[0] 
    output_file = os.path.join('/content/drive/MyDrive/Rutok/detect_txt', '{}.txt'.format(filename))
    file = open(output_file, 'w')
    image=os.path.join(image_path,image)
    image = read_image_bgr(image)
    draw = image.copy()
    draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)
    image = preprocess_image(image)
    image, scale = resize_image(image)
    
    start = time.time()
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
    images.append(image)
    print("processing time: ", time.time() - start)
    
    boxes /= scale
 
    for box, score, label in zip(boxes[0], scores[0], labels[0]):
        if score < 0.2:
          break
        box = box.astype("int")

        row = " ".join([LABELS[label], str(score),
                        str(box[1]), str(box[0]), str(box[3]), str(box[2])])
        
        file.write("{}\n".format(row))
    file.close()

Using TensorFlow backend.


tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-22.627417, -11.313708,  22.627417,  11.313708],
       [-28.50876 , -14.25438 ,  28.50876 ,  14.25438 ],
       [-35.918785, -17.959393,  35.918785,  17.959393],
       [-16.      , -16.      ,  16.      ,  16.      ],
       [-20.158737, -20.158737,  20.158737,  20.158737],
       [-25.398417, -25.398417,  25.398417,  25.398417],
       [-11.313708, -22.627417,  11.313708,  22.627417],
       [-14.25438 , -28.50876 ,  14.25438 ,  28.50876 ],
       [-17.959393, -35.918785,  17.959393,  35.918785]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-45.254833, -22.627417,  45.254833,  22.627417],
       [-57.01752 , -28.50876 ,  57.01752 ,  28.50876 ],
       [-71.83757 , -35.918785,  71.83757 ,  35.918785],
       [-32.      , -32.      ,  32.      ,  32.      ],
       [-40.317474, -40.317474,  40.317474,  40.317474],
       [-50.796833, -50.796833,  50.7

In [ ]:
!pip install rasterio

     |████████████████████████████████| 19.3 MB 62 kB/s 


In [ ]:
import tensorflow as tf
import rasterio as rio
from natsort import natsorted



# In[ ]:


# adjust this to point to your downloaded/trained model

model_path = "/content/drive/MyDrive/weights/resnet50_csv_23.h5"
image_path="/content/drive/MyDrive/tiles_jpg"
out_path="/content/drive/MyDrive/out"
# load retinanet model
model = models.load_model(model_path, backbone_name='resnet50')
model = models.convert_model(model)


# if the model is not converted to an inference model, use the line below
# see: https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model
# model = models.convert_model(model)

#print(model.summary())

# load label to names mapping for visualization purposes
labels_to_names = {0: '0'}


# ## Run detection on example

# In[ ]:


# load image
images=[]
image_no=1
i=1
for image in natsorted(os.listdir(image_path)):
    image=os.path.join(image_path,image)
    image=rio.open(image)
    image = image.read([1,2,3])
    draw = image.copy()
    #draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)
    #draw = cv2.cvtColor(draw, cv2.COLOR_RGB2BGR)
    #image = preprocess_image(image)
    #image, scale = resize_image(image)
    image=image.reshape(None, None, 3)

    
    start = time.time()
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
    images.append(image)
    print("processing time: ", time.time() - start)
    boxes /= scale
 

    for box, score, label in zip(boxes[0], scores[0], labels[0]):
        if score < 0.2:
          break

        color = label_color(label)

        b = box.astype(int)
        draw_box(draw, b, color=color)

        #caption = "{} {:.3f}".format(labels_to_names[label], score)
        #draw_caption(draw, b, caption)
        

        plt.imsave('/content/drive/MyDrive/out2/%d.jpg'%(len(images)),draw)

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-22.627417, -11.313708,  22.627417,  11.313708],
       [-28.50876 , -14.25438 ,  28.50876 ,  14.25438 ],
       [-35.918785, -17.959393,  35.918785,  17.959393],
       [-16.      , -16.      ,  16.      ,  16.      ],
       [-20.158737, -20.158737,  20.158737,  20.158737],
       [-25.398417, -25.398417,  25.398417,  25.398417],
       [-11.313708, -22.627417,  11.313708,  22.627417],
       [-14.25438 , -28.50876 ,  14.25438 ,  28.50876 ],
       [-17.959393, -35.918785,  17.959393,  35.918785]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-45.254833, -22.627417,  45.254833,  22.627417],
       [-57.01752 , -28.50876 ,  57.01752 ,  28.50876 ],
       [-71.83757 , -35.918785,  71.83757 ,  35.918785],
       [-32.      , -32.      ,  32.      ,  32.      ],
       [-40.317474, -40.317474,  40.317474,  40.317474],
       [-50.796833, -50.796833,  50.7

TypeError: ignored

In [ ]:
import rasterio
import numpy as np
import matplotlib.pyplot as plt

# Open the file:
raster = rasterio.open('/content/drive/MyDrive/Automate/input_tiff/Rutog_Clipped_tiff.tif')

# Normalize bands into 0.0 - 1.0 scale
#def normalize(array):
 #   array_min, array_max = array.min(), array.max()
  #  return (array - array_min) / (array_max - array_min)

# Convert to numpy arrays
nir = raster.read(3)
red = raster.read(2)
green = raster.read(1)

# Normalize band DN
#nir_norm = normalize(nir)
#red_norm = normalize(red)
#green_norm = normalize(green)

# Stack bands
nrg = np.dstack((nir, red, green))

# View the color composite
plt.imsave('/content/fhfhg.jpg',nrg)

ValueError: ignored